[llm]
# type ["google", "openai", "ollama", "grok", "mistral", "anthropic", "azure"]
type = "google"
cache = false

[ollama]
# model = "ollama/deepseek-r1"
# model = "ollama/deepseek-v2"
# model = "ollama/gemma3"
model = "ollama/mistral"
# model = "ollama/qwen3"

[google]
# model = "gemini/gemini-2.5-pro"
model = "gemini/gemini-2.5-flash-lite-preview-06-17"
