[general]
cache = true
throttling = true
rpm = 14

[llm]
types = [
    "anthropic",
    "google",
    "groq",
    "mistral",
    "ollama",
    "openai",
]
model = "gemini/gemini-2.5-flash-lite-preview-06-17"
type = "google"

[anthropic]
models = [
    'anthropic/claude-opus-4-20250514',
    'anthropic/claude-sonnet-4-20250514',
    'anthropic/claude-3-7-sonnet-20250219',
    'anthropic/claude-3-5-sonnet-20240620',
    'anthropic/claude-3-haiku-20240307',
    'anthropic/claude-3-opus-20240229',
    'anthropic/claude-3-sonnet-20240229',
    'anthropic/claude-2.1',
    'anthropic/claude-2',
    'anthropic/claude-instant-1.2',
    'anthropic/claude-instant-1',
]

[google]
models = [
    "gemini/gemini-2.5-pro",
    "gemini/gemini-2.5-flash-lite-preview-06-17",
]

[groq]
models = [
    "groq/llama-3.1-8b-instant",
    "groq/llama-3.1-70b-versatile",
    "groq/llama3-8b-8192",
    "groq/llama3-70b-8192",
    "groq/llama2-70b-4096",
    "groq/mixtral-8x7b-32768",
    "groq/gemma-7b-it",
    "groq/moonshotai/kimi-k2-instruct",
    "groq/qwen-qwq-32b",
]

[mistral]
models = [
    "mistral/mistral-small-latest",
    "mistral/mistral-medium-latest",
    "mistral/mistral-large-2407",
    "mistral/mistral-large-latest",
    "mistral/magistral-small-2506",
    "mistral/magistral-medium-2506",
    "mistral/open-mistral-7b",
    "mistral/open-mixtral-8x7b",
    "mistral/open-mixtral-8x22b",
    "mistral/codestral-latest",
    "mistral/open-mistral-nemo",
    "mistral/open-mistral-nemo-2407",
    "mistral/open-codestral-mamba",
    "mistral/codestral-mamba-latest"
]

[ollama]
models = [
    "ollama/codellama",
    "ollama/deepseek-coder-v2",
    "ollama/deepseek-r1",
    "ollama/deepseek-v2",
    "ollama/gemma3",
    "ollama/mistral",
    "ollama/qwen2.5-coder",
    "ollama/qwen3",
]

[openai]
models = [
    "gpt-4.1",
    "gpt-4.1-mini",
    "gpt-4.1-nano",
    "o4-mini",
    "o3-mini",
    "o3",
    "o1-mini",
    "o1-preview",
    "gpt-4o-mini",
    "gpt-4o-mini-2024-07-18",
    "gpt-4o",
    "gpt-4o-2024-08-06",
    "gpt-4o-2024-05-13",
    "gpt-4-turbo",
    "gpt-4-0125-preview",
    "gpt-4-0125-preview",
    "gpt-4-1106-preview",
    "gpt-3.5-turbo-1106",
    "gpt-3.5-turbo",
    "gpt-3.5-turbo-0301",
    "gpt-3.5-turbo-0613",
    "gpt-3.5-turbo-16k",
    "gpt-3.5-turbo-16k-0613",
    "gpt-4",
    "gpt-4-0314",
    "gpt-4-0613",
    "gpt-4-32k",
    "gpt-4-32k-0314",
    "gpt-4-32k-0613",
]
