[general]
cache = true
throttling = true
rpm = 14

[llm]
types = [
    "anthropic",
    "azure",
    "google",
    "grok",
    "mistral",
    "ollama",
    "openai",
]
model = "gemini/gemini-2.5-flash-lite-preview-06-17"
type = "google"

[anthropic]
models = [
    'claude-opus-4-20250514',
    'claude-sonnet-4-20250514',
    'claude-3-7-sonnet-20250219',
    'claude-3-5-sonnet-20240620',
    'claude-3-haiku-20240307',
    'claude-3-opus-20240229',
    'claude-3-sonnet-20240229',
    'claude-2.1',
    'claude-2',
    'claude-instant-1.2',
    'claude-instant-1',
]

[ollama]
models = [
    "ollama/codellama",
    "ollama/deepseek-coder-v2",
    "ollama/deepseek-r1",
    "ollama/deepseek-v2",
    "ollama/gemma3",
    "ollama/mistral",
    "ollama/qwen2.5-coder",
    "ollama/qwen3",
]

[google]
models = [
    "gemini/gemini-2.5-pro",
    "gemini/gemini-2.5-flash-lite-preview-06-17",
]
