[general]
cache = true
throttling = true
rpm = 14

[llm]
types = [
    "anthropic",
    "google",
    "groq",
    "mistral",
    "ollama",
    "openai",
]
model = "gemini/gemini-2.5-flash-lite-preview-06-17"
type = "google"

[anthropic]
models = [
    'anthropic/claude-opus-4-20250514',
    'anthropic/claude-sonnet-4-20250514',
    'anthropic/claude-3-7-sonnet-20250219',
    'anthropic/claude-3-5-sonnet-20240620',
    'anthropic/claude-3-haiku-20240307',
    'anthropic/claude-3-opus-20240229',
    'anthropic/claude-3-sonnet-20240229',
    'anthropic/claude-2.1',
    'anthropic/claude-2',
    'anthropic/claude-instant-1.2',
    'anthropic/claude-instant-1',
]

[groq]
models = [
    "groq/llama-3.1-8b-instant",
    "groq/llama-3.1-70b-versatile",
    "groq/llama3-8b-8192",
    "groq/llama3-70b-8192",
    "groq/llama2-70b-4096",
    "groq/mixtral-8x7b-32768",
    "groq/gemma-7b-it",
    "groq/moonshotai/kimi-k2-instruct",
    "groq/qwen-qwq-32b",
]

[ollama]
models = [
    "ollama/codellama",
    "ollama/deepseek-coder-v2",
    "ollama/deepseek-r1",
    "ollama/deepseek-v2",
    "ollama/gemma3",
    "ollama/mistral",
    "ollama/qwen2.5-coder",
    "ollama/qwen3",
]

[google]
models = [
    "gemini/gemini-2.5-pro",
    "gemini/gemini-2.5-flash-lite-preview-06-17",
]
