#!/bin/bash

script_dir="$(cd "$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")" && pwd)"

case "$1" in
	optimize)
		uv run optimizer/optimize.py
		;;
	reset)
		uv run optimizer/reset.py
		;;
	config)
		uv run config/menu.py
		;;
	bash)
		echo "$script_dir/dspick.bash"
		;;
	fish)
		echo "$script_dir/dspick.fish"
		;;
	zsh)
		echo "$script_dir/dspick.zsh"
		;;
	*)
		echo "Use:"
		echo "$(basename "$0") <optimize | reset | config | bash | fish | zsh>"
		echo "For shells (ex. bash): source \$($0 bash)"
		exit 1
		;;
esac
